language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t wyorusso/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run wyorusso/react-test npm test -- --coverage

after_success:
    - docker build -t wyorusso/multi-client ./client
    - docker build -t wyorusso/multi-nginx ./nginx
    - docker build -t wyorusso/multi-server ./server
    - docker build -t wyorusso/multi-worker ./worker
    # Log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push wyorusso/multi-client
    - docker push wyorusso/multi-nginx
    - docker push wyorusso/multi-server
    - docker push wyorusso/multi-worker

